services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /docker_data/express/mongo:/docker_data
    environment:
      MONGO_INITDB_DATABASE: express
