@api_url=http://localhost:8000/api/v1

### Health check
GET {{api_url}}/health

#### Register
POST {{api_url}}/auth/register
Content-Type: application/json

{
  "name": "username",
  "email": "hoangncd3@gmail.com",
  "password": "password"
}

#### Login
POST {{api_url}}/auth/login
Content-Type: application/json

{
  "email": "hoangncd3@gmail.com",
  "password": "password"
}

#### Refresh token
POST {{api_url}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQ1NmE5NmMyY2FiZGRhMjYyNGMxMzAiLCJpYXQiOjE3MzI2MDUwMjUsImV4cCI6MTczNTE5NzAyNX0.qyLnZ0tSgvfEFLxV4gg75EVYfoeB9phFLl4GKMrJ_0nBakjTXfB-ntH7n8azXnLi6NcMKLL5-Ko3gSDxCIbduaKImooamIb-ossy6nQeAv2n2fZvUAawk9RDJaADV1XJWWd4GBQr4BFwag7feByfWKUTk0d-huQAxKmn2GyrT9KKU_aMRk6wLg2FF8p44iYPx1N1o1kZcFnmB_g4pagun577kOPs_lWNuOjb9U8kzEYTvAv9N4mJTPcsFLWQRMyMK9mnOXLNRpRaidtkOZOFztQtAU-hMtu_cjkNBTjfbdOE0P20cx91IA78h_IAlpe_Bg68LxkvPskhTj3c8qkJo-RSZy71nHGkCojyuQlx0qz_M3OE2_PRT8ywWsDlen_820IR_WnvJwgu6gMRf4jxuWh1ZfyOjXwVl9EE0FrxZAleQJep5IFufW78ssFYUHH-SoF_XuZ8yDY7DAhhmwKlohFz2agOnxbCvGd8lEeQ7BAfb_SL8-Jx9NojxJAlBdUT2420KstnfEsTu6mAQRTVYgTnQ-o5bjcvsVhoW-1QHW40dGty6rVkSTvKfAqLfzrI6edbr9K44m37HeSvEYK9WOZ3XWVEp1ORjFk9guTiP4Ts5bz5rdXAP-k8_Jk5X5Nq0jQSe3PJwfqWNOh6UqNgKNIW-zdDlLOgoxNDzK85KAo"
}