@api_url=http://localhost:8000/api/v1
@x_access_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQ1NmE5NmMyY2FiZGRhMjYyNGMxMzAiLCJpYXQiOjE3MzI2OTI5NzUsImV4cCI6MTczMjY5Mzg3NX0.WRlPvEIxM0GCSm-3dvgHhJ6wnsWSs4Gtr_JezjevurC8a24_XAQyC0QKMiLkAoW_BFvdn99sB6ns0CCcT1zC3-TKyGsqq7UV1EqBpQeY-4xoHsYUwTfdv9bpiqRome4WfHPx-jnjN5bG3AmUl3wqmVkP7NVdPGeZVHsUBB7KotoOXrqhysZUO5JlHKFz4ul-l933OoSezrgMSJMFE1Ee3YOaULSrXG4CwTGyF5MRWbld_beY54TTula6WmUKG6NysR3hYZItDm4wCF3lgPj67zOZoPEZRHIfMLW-gSxn-oryRAK_XxlGsiO61kCtqH2D2rvOdg5QDEENs28jf6vyjTUaKPBMybhoEuvF55KHhcEY7imfN58BhXUAU4dXwNk7nnAfn01NyV5GdHnWklKFaLpXGkGeNvbc7QeSdWdSocUUmwAVUP63iCYxU33m_Y3EyIhSTu7j5kpxsC5kNTCIYrTCZoCuiS5e5vFeQDXGBDyFkvRyc5tlgrlmsYitL824R3NFIP5i-ZlsW4xSDWeDdSQ5jqbJVlKQ3n2_RsE0KGOXN7c-oHbPUnY27AXxbzR0yPxu6zun7EJcnpNsd5O7aDNdaC1WaBRDGaeNYXpVYkVbF2JfMgY9Mpf4jf_Jo9csFr0Tfa8y831N_cynu7gUXMrJkyLRRzJhxbressOAa_A
@x_refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQ1NmE5NmMyY2FiZGRhMjYyNGMxMzAiLCJpYXQiOjE3MzI2OTI5NzUsImV4cCI6MTczNTI4NDk3NX0.KAhlLR93w36wyXtK8b1z1P2rvmD8BkBwTWZVQ4ofXPPTCmZf2rKFeZyfyTPfwOti8IB3M8RABpEhDHBAjsJ_1N5PSgslWKK0DpDSkVEKXmhpg0dklHp1UFzEcd_RQbXijF5xYh13mg-DAPltS4IRMrB8GYCrxUcy5f4fNAfAxet_UatgYvelb4-jgkqdYomdW0doUe47se-1GAMG_Hhg_ULygX9RIRZKzJR0cL_v6nWQKBk4g-Lg_x7ke_uYck-GcPU-Ie5sH-4MC7C_seSJz0IRk_JepNqVds0vUGggakH2cJ-wuQ15ZASFVmmks6tNK7hy2RRVyPWfRzsn2oCjnzEYegpBHr-vz6rGcCJDLKhExcLSoYLbzc9nUWDZHG1ZSMjoiC0PLEa50ooz-N_y71ErfnUxHk7I6hGRta-ZkQ1hp-PxxSmEeFrxDNpA0KyoSV4kWHxv3J9i8RKHLfg_qQdUGwbuU4vLuCGdFBJZBfvWbVsTT-8LONsp1TM8Dy_V9K70bQR8abzxm-fma-ujjEi5qM6p7Oolqn2M29z7pfyVY6IVYjakm_USSmfik6bZQnLF4RQo3B9SLJ5-X4MvcThQyQ4rXAhPvAZ7LfoCA12N1M3Er6UdcqhIh7C6ybd8o4--CPoteMl8GQ9VoOWufIbE_jfZVDm5zsYHb-xNcPk
@x_client_id=67456a96c2cabdda2624c130

### Health check
GET {{api_url}}/health

#### Register
POST {{api_url}}/auth/register
Content-Type: application/json

{
  "name": "username",
  "email": "hoangncd3@gmail.com",
  "password": "password"
}

#### Login
POST {{api_url}}/auth/login
Content-Type: application/json

{
  "email": "hoangncd3@gmail.com",
  "password": "password"
}

#### Refresh token
POST {{api_url}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQ1NmE5NmMyY2FiZGRhMjYyNGMxMzAiLCJpYXQiOjE3MzI2MDUwMjUsImV4cCI6MTczNTE5NzAyNX0.qyLnZ0tSgvfEFLxV4gg75EVYfoeB9phFLl4GKMrJ_0nBakjTXfB-ntH7n8azXnLi6NcMKLL5-Ko3gSDxCIbduaKImooamIb-ossy6nQeAv2n2fZvUAawk9RDJaADV1XJWWd4GBQr4BFwag7feByfWKUTk0d-huQAxKmn2GyrT9KKU_aMRk6wLg2FF8p44iYPx1N1o1kZcFnmB_g4pagun577kOPs_lWNuOjb9U8kzEYTvAv9N4mJTPcsFLWQRMyMK9mnOXLNRpRaidtkOZOFztQtAU-hMtu_cjkNBTjfbdOE0P20cx91IA78h_IAlpe_Bg68LxkvPskhTj3c8qkJo-RSZy71nHGkCojyuQlx0qz_M3OE2_PRT8ywWsDlen_820IR_WnvJwgu6gMRf4jxuWh1ZfyOjXwVl9EE0FrxZAleQJep5IFufW78ssFYUHH-SoF_XuZ8yDY7DAhhmwKlohFz2agOnxbCvGd8lEeQ7BAfb_SL8-Jx9NojxJAlBdUT2420KstnfEsTu6mAQRTVYgTnQ-o5bjcvsVhoW-1QHW40dGty6rVkSTvKfAqLfzrI6edbr9K44m37HeSvEYK9WOZ3XWVEp1ORjFk9guTiP4Ts5bz5rdXAP-k8_Jk5X5Nq0jQSe3PJwfqWNOh6UqNgKNIW-zdDlLOgoxNDzK85KAo"
}

### Logout
POST {{api_url}}/auth/logout
Content-Type: application/json
x-client-id: 67456a96c2cabdda2624c130
x-refresh-token: {{x_refresh_token}}
Authorization: Bearer {{x_access_token}}

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzQ1NmE5NmMyY2FiZGRhMjYyNGMxMzAiLCJpYXQiOjE3MzI2MDg0ODQsImV4cCI6MTczNTIwMDQ4NH0.Ayx80Wbt4zE_tGbVmxTD_C6cXONkPNaQNrcKSYIXHiRXZRBKKd28oJr3lgRNCwUehQrqVbdrksjuN96-0e0YN3OGf4BjyoCf1D3F66YxA5K7_yPfjYdQ4V5kGEaW8wA759ihioTeVmSo9z4gY6_AM2V4Laj7tx9x-etm_znMdFcNdRRxrkDCPl8V7PYVJhFhdu5TeXwO--vFpK965IoGhzdlqdWiY9wbin1vnEEIUAEHkT_LZYrE_AXxSbG6HjYqMfktssrVjCZoZ9TecY9jQOFeSIVn_3zXGb4PKxJTb498noiJO0duDFlbM4sVG_I1Mz69B5D3KW-DYzzSXZt61Oc6-KxcUB3q9_LNrRcK48ZLwrfA1UZaopf1yGSkt9_1Wk5Fx_AT_8uXxpZbdOyOskeI_jxYFvUGxOamryldvbz2JBrOZUEXkdlOYXGh-A1MMSv4gVZLYAc-6OabMQnJCVLJvBst707YRQuhGEWtNYS2Fc4Dkwv2sDEz-_RuCvuVmCPFwpr6jsBQ-x_VhWJqzijHLA8K6tpDu0B2puhXUBOn9IG9v3TKU3b9kIxYlJcabiKmV1dzS5MQVDbRYpm-rLkVV8SQbB7dnFOWnQNwTxBBxOQd6PpgAP__qcntrm0APs3GXsUJxUG57VckfF5v8zhLB8CyLZ3xEY0Fnb4ekGc"
}

### Create product
POST {{api_url}}/product
Content-Type: application/json
x-client-id: 67456a96c2cabdda2624c130
x-refresh-token: {{x_refresh_token}}
Authorization: Bearer {{x_access_token}}

{
  "name": "Product 6",
  "thumbnail": "https://example.com/product1.jpg",
  "description": "Description of product 6",
  "price": 19.99,
  "quantity": 10,
  "type": "furniture",
  "attributes": {
    "brand": "Brand 44xs",
    "size": "Large",
    "material": "Wood"
  }
}